### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by edbizarro** [Solshal/solshal-chrome-extension#18]
This site can’t be reached
www.solshal.com refused to connect.

**Comment by weblancaster** [comment]
Yes, I'm looking in to fix the issue. Thanks for letting me know @edbizarro

**Comment by weblancaster** [comment]
@edbizarro it's back to normal now. Sorry for the inconvenience.

I need to setup an alert when this stuff happens because I noticed was 15mins ago.

**Comment by edbizarro** [comment]
Nice!

I use https://uptimerobot.com

**Comment by weblancaster** [comment]
Awesome. I was going to built one but going to give a try to uptimerobot first.

Thanks.
